version: "3.9"
services:
    nestapp:
        container_name: nestapp
        image: kirill/nestjs
        volumes:
            - type: bind
              source: .
              target: /app
        build: .
        ports:
            - 3001:3001
